name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List all files recursively
      run: find . -type f

    - name: Grant execute permissions for gradlew
      run: chmod +x ./Ultimit_X_O/gradlew

    - name: Build with Gradle
      run: ./Ultimit_X_O/gradlew build
