name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # Use 'zulu' as the JDK distribution
        java-version: '11'   # Specify the Java version you are using

    - name: Build with Gradle
      run: ./gradlew build
