name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - List all files recursively
        run: find . -type f

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set working directory to Ultimit_X_O
        working-directory: ./Ultimit_X_O
        run: echo "Changed working directory to Ultimit_X_O"

      - name: Grant execute permissions for gradlew
        working-directory: ./Ultimit_X_O
        run: chmod +x gradlew

      - name: Verify Gradle Wrapper
        working-directory: ./Ultimit_X_O
        run: ./gradlew --version

      - name: Build with Gradle
        working-directory: ./Ultimit_X_O
        run: ./gradlew build
